# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SicrediChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SicrediChallenge
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SicrediChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SicrediChallengeUITests' do
    # Pods for testing
  end

end
